### ISSUE TITLE
Rename init_valid_moves to init_empty_cells

### ISSUE THREAD

**Issue by EXC3ll3NTrhyTHM** [Advanced-Software-Engineering-UMKC/Nine-Mens-Morris#20]
Reference https://github.com/Advanced-Software-Engineering-UMKC/Nine-Mens-Morris/pull/17/files#r1785544216

**Comment by raspberrymilkyway** [comment]
Might want to rename the self.valid_moves variable too -- it's all valid moves on an empty board.
