### ISSUE TITLE
Investigate issue with get_cell_clicked in while loop

### ISSUE THREAD

**Issue by EXC3ll3NTrhyTHM** [Advanced-Software-Engineering-UMKC/Nine-Mens-Morris#21]
Reference https://github.com/Advanced-Software-Engineering-UMKC/Nine-Mens-Morris/pull/17/files#r1786976373

We think this could be placed in a better place or just done in a better way.

**Comment by raspberrymilkyway** [comment]
Think Suryansh fixed this
