### ISSUE TITLE
Implementation tasks - Planning Poker

### ISSUE THREAD

**Issue by raspberrymilkyway** [Advanced-Software-Engineering-UMKC/Nine-Mens-Morris#3]
Describe the production code, automated test code, or manual test case for each user story and acceptance criterion related to the implementation of the primitive functions, i.e., board object and visualization and piece placement for both players. 

For each acceptance criterion of every user story for the primitive functions, you need to implement at least one test (either test code or manual test case).

**Comment by EXC3ll3NTrhyTHM** [comment]
I think this task should instead be to perform planning poker then we create separate issues from the user stories for each implementation item.
