### ISSUE TITLE
Creating the piece placement class

### ISSUE THREAD

**Issue by EXC3ll3NTrhyTHM** [Advanced-Software-Engineering-UMKC/Nine-Mens-Morris#8]

**Comment by EXC3ll3NTrhyTHM** [comment]
- - current turn, name of the player
- - which piece is in the position

**Comment by EXC3ll3NTrhyTHM** [comment]
can follow how they do this here https://www.youtube.com/watch?v=q_Nzuyvf3tw

**Comment by EXC3ll3NTrhyTHM** [comment]
I left off at about the 2:64 mark in the video. I skipped over updating the cell and drawing the piece. Hopefully its pretty straight forward what to do next. If not let me know and I can help.

**Comment by raspberrymilkyway** [comment]
The video was super helpful for the GUI part, but it didn't really mesh with how I ended up doing the piece placement work.

_Piece.py_ has a class called "Pieces" that work for piece placement

**Comment by EXC3ll3NTrhyTHM** [comment]
That makes sense. 

I added a couple comments on the PR.

https://github.com/Advanced-Software-Engineering-UMKC/Nine-Mens-Morris/pull/17/files

**Comment by raspberrymilkyway** [comment]
Wait, where are those comments? I don't see them.
